import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/admin/AdminSidebar";
import HeaderSub from "@/components/common/HeaderSub";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Admin Dashboard Layout",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full antialiased">
            <body>
                <HeaderSub className="m-8" hNumber={1} header="Admin Dashboard" sub="" />

                <div className="m-8 flex gap-8">
                    <div className="w-1/5">
                        <AdminSidebar items={[
                            { href: "/", label: "Website Home" },
                            { href: "/admin", label: "Dashboard" },
                            { href: "/admin/users", label: "Users" },
                            { href: "/admin/courses", label: "Courses" },
                            { href: "/admin/sales", label: "Sales" },
                        ]} />
                    </div>
                    <div className="flex-1 mx-8">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
