import type { Database } from "@/types/supabase";

// define all db types (generated by supabase cli) in one place

export type AccountRow = Database["public"]["Tables"]["account"]["Row"];

export type InstructorRow = Database["public"]["Tables"]["instructor"]["Row"];
export type TagRow = Database["public"]["Tables"]["tag"]["Row"];

export type CourseRow = Database["public"]["Tables"]["course"]["Row"];
export type SectionRow = Database["public"]["Tables"]["section"]["Row"];
export type LessonRow = Database["public"]["Tables"]["lesson"]["Row"];

export type EnrollmentRow = Database["public"]["Tables"]["enrollment"]["Row"];
export type ProgressRow = Database["public"]["Tables"]["progress"]["Row"];

export type ActivityRow = Database["public"]["Tables"]["activity"]["Row"];
export type UserRoleRow = Database["public"]["Tables"]["user_roles"]["Row"];

export type EnrollmentOrder = {
    account_id: string;
    course_id: number;
    created_at: string;
    price: number;
}